### ISSUE TITLE
First note in fever is not added to the fever note count

### ISSUE THREAD

**Issue by Smanmos** [xfl03/SekaiMusicMeta#1]
https://github.com/xfl03/SekaiMusicMeta/blob/a11d907cb8a01992e6da2c8577582fe4262cd252/metaConvert.ts#L71-L89

When the fever starts, the program is in the else {} block. This means that feverNoteCount is not updated.

**Comment by xfl03** [comment]
Thanks for the issue, it will be fixed.

**Comment by xfl03** [comment]
https://github.com/xfl03/SekaiMusicMeta/commit/fa74b7809e107d6532f0f7476dfe16d829f00fcf
